f1 = float(input("Enter 1st decimal number:"))
f2 = float(input("Enter 2nd decimal number:"))
f3 = float(input("Enter 3rd decimal number:"))
f4 = float(input("Enter 5th decimal number:"))
f5 = float(input("Enter 5th decimal number:"))
f6 = float(input("Enter 6th decimal number:"))
f7 = float(input("Enter 7th decimal number:"))
f8 = float(input("Enter 8th decimal number:"))
f9 = float(input("Enter 9th decimal number:"))
f10 = float(input("Enter 10th decimal number:"))
val = float(f1+f2+f3+f4+f5+f6+f7+f8+f9+f10)
print("sum: "+str(val))
print("avg: "+str(val/10))
